name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: bazel build //src/... --repo_env=CC=clang

      - name: Test
        run: bazel test //src:vulpes_tests --repo_env=CC=clang
